arch:
  _target_: models.tensor_nerf.TensorNeRF
  _partial_: True

  alphaMask_thres: 0.0001
  rayMarch_weight_thres: 0.0001
  max_recurs: 2
  roughness_rays: 200
  infinity_border: False
  appdim_noise_std: 0.0
  world_bounces: 0
  max_normal_similarity: 0.99
  max_floater_loss: 1
  selector:
    _target_: modules.pt_selectors.TopNWeight
    max_selected: 1500000
    bounces_per_ray: 1000
    weight_thres: 1e-3
    eps: 1e-1

  sampler:
    _target_: samplers.continuous_alphagrid.ContinuousAlphagrid
    _partial_: True
    multiplier: 1
    dynamic_batchsize: False
    sample_mode: multi_jitter
    test_sample_mode: midpoint
    threshold: 0.0001
    grid_size: 128
    bound: 1.5

    # _target_: samplers.alphagrid.AlphaGridSampler
    # _partial_: True
    # enable_alpha_mask: False
    # nEnvSamples: 0
    # update_list: [4000, 8000]
    # multiplier: 1
    # threshold: 0.0001

    # _target_: samplers.raymarch.Raymarcher
    # _partial_: True
    # max_samples: 100000
    # grid_size: 256
    # max_steps: 1024

  rf: 'placeholder'

  brdf_sampler:
    _target_: models.brdf.GGXSampler
    _partial_: True

  tonemap:
    # _target_: models.tonemap.HDRTonemap
    # _target_: models.tonemap.LinearTonemap
    _target_: models.tonemap.SRGBTonemap

  brdf:
    _target_: models.brdf.MLPBRDF
    _partial_: True
    # pbr: True

    # v_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4]
    # l_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4]
    # num_layers: 4
    # feape: 0
    # featureC: 128
    num_layers: 4
    feape: 0
    featureC: 64
    activation: 'softplus'
    mul_ggx: False
    use_roughness: true
    detach_roughness: false
    lr: 1e-2

  bg_module:
    _target_: models.bg_modules.HierarchicalCubeMap
    bg_resolution: 1024
    mipbias: -1
    num_levels: 1
    activation: 'softplus'
    power: 2
    stds: []
    lr: 0.05
    mipbias_lr: 1e-4

  diffuse_module:
    _partial_: True
    _target_: models.render_modules.MLPDiffuse
    pospe: 0
    feape: 0
    featureC: 64
    num_layers: 3
    lr: 1e-4

  normal_module:
    _partial_: True
    _target_: models.render_modules.MLPNormal
    lr: 1e-3
    pospe: 0
    feape: 0
    featureC: 64
    num_layers: 3

params:
  lambda_start: 0.0
  lambda_end: 0.0
  smoothing_list: [10000, 15000, 20000]

  # bounce_n_list: [100, 1000, 10000, 20000]
  # bounce_iter_list: [9000, 12000, 14000]

  bounce_n_list: [0, 100000]
  # bounce_iter_list: [4500]
  bounce_iter_list: [0]

  num_bw_iters: 0

  #upsamp_list: [2000,3000,4000,5500,7000]
  #uplambda_list: [7000, 12000, 17000, 21000]
  #uplambda_list: [7000, 12000, 17000]
  uplambda_list: [7000, 10000, 12000]
  L1_weight_inital: 8e-5
  L1_weight_rest: 4e-5

  TV_weight_density: 0.0
  TV_weight_app: 0.0
  normal_lambda: 3e-3
  diffuse_lambda: 0
  backwards_rays_lambda: 0.1
  floater_lambda: 1e-3
  # floater_lambda: 0.00001
  charbonier_eps: 1e-3
  ortho_weight: 0

  envmap_train_start: 20
  # num_rays_per_envmap: 512
  num_rays_per_envmap: 64
  num_env_train_iters: 0
  n_iters: 30000
  charbonier_loss: false
  start_density: 1e-2
  lr_init: 0.02
  batch_size: 4096
