arch:
  _target_: modules.tensor_nerf.TensorNeRF
  _partial_: True

  recur_alpha_thres: 1e-3
  lr_scale: 1
  infinity_border: False
  eval_batch_size: 4096
  recur_stepmul: 0.1

  bg_noise: 0.0
  bg_noise_decay: 0.999

  use_predicted_normals: False
  orient_world_normals: True
  align_pred_norms: True
  detach_inter: False
  geonorm_iters: 10000

  tonemap:
    # _target_: modules.tonemap.HDRTonemap
    # _target_: modules.tonemap.LinearTonemap
    _target_: modules.tonemap.SRGBTonemap

#   sampler:
#     _target_: samplers.continuous_alphagrid.ContinuousAlphagrid
#     _partial_: True
#     # multipliers: [1, 2]
#     # multiplier_iters: [1000]
#     multipliers: [1]
#     multiplier_iters: []
#     shrink_iters: [2000, 4000]
#     dynamic_batchsize: True
#     # sample_mode: multi_jitter
#     sample_mode: single_jitter
#     test_sample_mode: midpoint
#     # threshold: 5e-5
#     threshold: 1e-4
#     grid_size: 256
#     update_freq: 16
#     max_samples: 200000
#     conv: 2
#     bound: 1.5

  sampler:
    _target_: samplers.nerf_acc.NerfAccSampler
    _partial_: True
    grid_size: 128
    update_freq: 16
    multiplier: 2
    ema_decay: 0.95
    occ_thre: 0.01
    alpha_thres: 1e-4
    max_samples: -1

  normal_module:
    _partial_: True
    _target_: modules.render_modules.MLPNormal
    lr: 1e-3
    # pospe: -1
    # feape: 2
    # pospe: 0
    pospe: -1
    feape: 0

    hidden_w: 64
    num_layers: 3
    initializer: 'kaiming'
    size_multi: 2.5e-3
    # allocation: 3
    offset_geometry: False

  model:
    _partial_: True
    _target_: models.realbounce.RealBounce
    percent_bright: 0.05
    # max_brdf_rays: [3194304]
    max_brdf_rays: [259430]
    target_num_samples: [800000]
    russian_roulette: False
    max_retrace_rays: []
    cold_start_bg_iters: 0
    detach_N_iters: 0
    anoise: 0.25

    # bright_sampler:
    #   _target_: modules.bright_sampler.BrightnessImportanceSampler
    #   _partial_: True
    #   scale: 10
    #   update_freq: 50

    brdf_sampler:
      _target_: brdf_samplers.ggx.GGXSampler
      _partial_: True

    # brdf_sampler:
    #   _target_: brdf_samplers.multisampler.MultiSampler
    #   _partial_: True
    #   sampler1:
    #     _target_: brdf_samplers.ggx.GGXSampler
    #     _partial_: True
    #   sampler2:
    #     _target_: brdf_samplers.ggx.GGXSampler
    #     _partial_: True

    brdf:
      _target_: modules.brdf.MLPBRDF
      _partial_: True
      # pbr: True

      # v_encoder:
      #   _target_: modules.ish.ListISH
      #   degs: [0,1,2,4]
      # l_encoder:
      #   _target_: modules.ish.ListISH
      #   degs: [0,1,2,4]
      # num_layers: 4
      # feape: 0
      # featureC: 128
      mul_LdotN: False
      feape: 0
      dotpe: -1
      # h_encoder:
      #   _target_: modules.render_modules.PE
      #   max_degree: 2
      # d_encoder:
      #   _target_: modules.render_modules.PE
      #   max_degree: 2
      h_encoder:
        _target_: modules.ish.ListISH
        degs: [0,1,2,4]
      d_encoder:
        _target_: modules.ish.ListISH
        degs: [0,1,2,4]
      hidden_w: 64
      num_layers: 4
      initializer: 'kaiming'

      # num_layers: 4
      # dotpe: 6
      # featureC: 128
      # activation: 'sigexp'
      bias: 0
      activation: 'sigmoid'
      # activation: 'sigmoid'
      lr: 1e-3

    diffuse_module:
      _partial_: True
      _target_: modules.render_modules.HydraMLPDiffuse
      pospe: -1
      feape: 0
      # pospe: 12
      # feape: 0
      # view_encoder:
      #   _target_: modules.render_modules.PE
      #   max_degree: 2
      roughness_view_encoder:
        _target_: modules.render_modules.PE
        max_degree: 2
      roughness_cfg:
        hidden_w: 64
        num_layers: 2
      hidden_w: 64
      num_layers: 1
      initializer: 'xavier_sigmoid'
      lr: 1e-3
      start_roughness: 0.35
      tint_bias: -1.1
      diffuse_bias: -0.619
      diffuse_mul: 1.5
      roughness_bias: -1
      # allocation: 7

    visibility_module: NULL
    # visibility_module:
      # _target_: modules.naive_vis_cache.NaiveVisCache
      # grid_size: 128
      # midpoint: 128
      # jump: 4

    bright_sampler:
      _target_: brdf_samplers.equirect_bright_sampler.ERBrightSampler

  bg_module:
    _target_: modules.integral_equirect.IntegralEquirect
    bg_resolution: 1024
    mipbias: 0
    activation: 'exp'
    lr: 0.02
    init_val: -0.6
    # init_val: -0.602
    mul_lr: 0
    brightness_lr: 0
    betas: [0.9, 0.99]
    mul_betas: [0.9, 0.9]
    mipbias_lr: 1e-4
    mipnoise: 0.0

  rf: 'placeholder'

params:
  L1_weight_initial: 0
  L1_weight_rest: 0
  clip_grad: 10
  weight_decay: 1e-6
  eps: 1e-15
  betas: [0.9, 0.99]

  starting_batch_size: 100
  min_batch_size: 4096
  target_num_samples: 400000

  TV_weight_density: 0.0
  TV_weight_app: 0.0
  TV_weight_bg: 0
  envmap_lambda: 0
  pred_lambda: 3e-2
  final_pred_lambda: 3e-4
  diffuse_lambda: 0
  ori_lambda: 0.05
  final_ori_lambda: Null
  brdf_lambda: 0
  normal_err_lambda: 0
  
  distortion_lambda: 0 # 1e-3
  visibility_lambda: 0
  # distortion_lambda: 0.00001
  charbonier_eps: 1e-3
  ortho_weight: 0
  N_visibility_rays: 128

  n_iters: 30000
  charbonier_loss: false
  start_density: 5e-3
  batch_size: 4096
  lr: Null

  # configure decay
  lr_init: 1
  lr_final: 1e-3
  lr_delay_mult: 0.1
  lr_delay_steps: 100

  bg_col: 'white'
