arch:
  _target_: modules.tensor_nerf.TensorNeRF
  _partial_: True

  rayMarch_weight_thres: 1e-4
  recur_weight_thres: 1e-4
  lr_scale: 1
  infinity_border: False
  eval_batch_size: 4096

  bg_noise: 0.0
  bg_noise_decay: 0.999

  use_predicted_normals: True
  orient_world_normals: False
  detach_inter: True

  tonemap:
    # _target_: modules.tonemap.HDRTonemap
    # _target_: modules.tonemap.LinearTonemap
    _target_: modules.tonemap.SRGBTonemap

  sampler:
    _target_: samplers.continuous_alphagrid.ContinuousAlphagrid
    _partial_: True
    multiplier: 1
    shrink_iters: []
    dynamic_batchsize: True
    # sample_mode: multi_jitter
    sample_mode: single_jitter
    test_sample_mode: midpoint
    # threshold: 5e-5
    threshold: 1e-4
    grid_size: 256
    max_samples: 200000
    conv: 10
    bound: 1.5

  normal_module:
    _partial_: True
    _target_: modules.render_modules.MLPNormal
    lr: 1e-3
    # pospe: -1
    # feape: 2
    # pospe: 0
    pospe: -1
    feape: 0

    hidden_w: 64
    num_layers: 3
    initializer: 'kaiming'
    size_multi: 2.5e-3
    # allocation: 3
    offset_geometry: False

  model:
    _partial_: True
    _target_: models.realbounce.RealBounce
    percent_bright: 0.1
    max_brdf_rays: [3194304]
    cold_start_bg_iters: 0
    detach_N_iters: 250
    anoise: 0.0

    # bright_sampler:
    #   _target_: modules.bright_sampler.BrightnessImportanceSampler
    #   _partial_: True
    #   scale: 10
    #   update_freq: 50

    brdf_sampler:
      _target_: brdf_samplers.ggx.GGXSampler
      # _target_: modules.brdf.CosineLobeSampler
      # _target_: modules.brdf.BeckmannSampler
      _partial_: True

    brdf:
      _target_: modules.brdf.MLPBRDF
      _partial_: True
      # pbr: True

      # v_encoder:
      #   _target_: modules.ish.ListISH
      #   degs: [0,1,2,4]
      # l_encoder:
      #   _target_: modules.ish.ListISH
      #   degs: [0,1,2,4]
      # num_layers: 4
      # feape: 0
      # featureC: 128
      mul_LdotN: False
      feape: 0
      dotpe: -1
      # h_encoder:
      #   _target_: modules.render_modules.PE
      #   max_degree: 2
      # d_encoder:
      #   _target_: modules.render_modules.PE
      #   max_degree: 2
      h_encoder:
        _target_: modules.ish.ListISH
        degs: [0,1,2,4]
      d_encoder:
        _target_: modules.ish.ListISH
        degs: [0,1,2,4]
      hidden_w: 64
      num_layers: 4
      initializer: 'kaiming'

      # num_layers: 4
      # dotpe: 6
      # featureC: 128
      # activation: 'sigexp'
      bias: -1.1
      activation: 'sigmoid'
      # activation: 'sigmoid'
      lr: 1e-3

    diffuse_module:
      _partial_: True
      _target_: modules.render_modules.HydraMLPDiffuse
      pospe: -1
      feape: 0
      # pospe: 12
      # feape: 0
      # view_encoder:
      #   _target_: modules.render_modules.PE
      #   max_degree: 2
      hidden_w: 64
      num_layers: 1
      initializer: 'xavier_sigmoid'
      lr: 1e-3
      tint_bias: -1.1
      diffuse_bias: -1.1
      diffuse_mul: 1.5
      roughness_bias: -1
      # allocation: 7

  bg_module:
    _target_: modules.bg_modules.HierarchicalCubeMap
    bg_resolution: 512
    mipbias: 0
    num_levels: 1
    TV_max_scale: 1
    activation: 'exp'
    power: 2
    stds: []
    lr: 0.1
    init_val: 0
    mul_lr: 0
    brightness_lr: 0
    betas: [0.0, 0.0]
    mul_betas: [0.9, 0.9]
    mipbias_lr: 1e-4
    mipnoise: 0.0

  rf: 'placeholder'

params:
  L1_weight_initial: 0
  L1_weight_rest: 0
  clip_grad: 10
  weight_decay: 1e-6
  eps: 1e-15
  betas: [0.9, 0.99]

  TV_weight_density: 0.0
  TV_weight_app: 0.0
  TV_weight_bg: 0
  envmap_lambda: 5e-5
  pred_lambda: 3e-4
  final_pred_lambda: Null
  diffuse_lambda: 0
  ori_lambda: 0.01
  final_ori_lambda: Null
  brdf_lambda: 0
  
  distortion_lambda: 0 # 1e-3
  visibility_lambda: 0
  # distortion_lambda: 0.00001
  charbonier_eps: 1e-3
  ortho_weight: 0
  N_visibility_rays: 128

  n_iters: 30000
  charbonier_loss: false
  start_density: 2.5e-3
  # batch_size: 4096
  batch_size: 16384
  lr: Null

  # configure decay
  lr_init: 1
  lr_final: 1e-3
  lr_delay_mult: 0.1
  lr_delay_steps: 100

