_partial_: True
_target_: fields.tensoRF.TensorVMSplit
distance_scale: 25
density_n_comp: 16
appearance_n_comp: 24
app_dim: 24
step_ratio: 0.5
density_res_multi: 1
contract_space: False
smoothing: 1.5
# activation: 'softplus_shift'
activation: 'softplus'
# activation: 'relu_shift'
density_shift: -10

N_voxel_init: 2097156 # 128**3
# N_voxel_final: 27000000 # 300**3
# N_voxel_init: 27000000 # 128**3
N_voxel_final: 134217728 # 512**3
upsamp_list: [4000,4000,5500,7000]
lr: 1e-2
lr_net: 1e-3
num_pretrain: 1000
